import { useEffect, useState, type FormEvent } from "react";
import { useQuery } from "@tanstack/react-query";
import { useSearchParams } from "react-router-dom";
import { DateTime } from "luxon";
import { api, ApiError } from "../api/client";
import type { Direction, Note, NoteListParams, SortField, Tag } from "../api/contracts";
import { queryKeys } from "../api/query-keys";
import { useNoteMutations, useSettingsMutation, useTagMutations } from "../api/mutations";
import { Button } from "../components/ui/button";
import { Field, Input } from "../components/ui/input";
import { NoteForm } from "../features/notes/note-form";
import { searchSchema, settingsFormSchema, tagFormSchema } from "../forms/schemas";
import { CalendarView } from "../features/calendar/calendar-view";
import { UpcomingView } from "../features/upcoming/upcoming-view";
import { SeriesForm, RecurringEditChoice } from "../features/recurrence/series-form";
import { parseNoteParams, serializeNoteParams } from "../features/notes/note-filter-params";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "../components/ui/dialog";

function Screen({title,description,action,children}:{title:string;description:string;action?:React.ReactNode;children?:React.ReactNode}){return <section><header className="mb-6 flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">{title}</h1><p className="mt-1 text-slate-600">{description}</p></div>{action}</header>{children??<Empty label="This workspace is ready for feature integration."/>}</section>}
const ErrorMessage=({error,label="Request failed."}:{error:unknown;label?:string})=><p role="alert" className="rounded bg-red-50 p-3 text-red-800">{error instanceof ApiError?error.body.message:label}</p>;
export function CalendarScreen(){const settings=useQuery({queryKey:queryKeys.settings.all,queryFn:api.settings.get});const tags=useQuery({queryKey:queryKeys.tags.all,queryFn:api.tags.list});return <Screen title="Calendar" description="Month, week, and day schedule views.">{settings.isPending?<p role="status">Loading calendar…</p>:settings.isError?<ErrorMessage error={settings.error}/>:<CalendarView timezone={settings.data.timezone} tags={tags.data??[]}/>}</Screen>}

export function NotesScreen(){
 const [url,setUrl]=useSearchParams();const params=parseNoteParams(url);const [search,setSearch]=useState(params.q??"");const [searchError,setSearchError]=useState("");const [editing,setEditing]=useState<Note|"new"|"series"|null>(null);
 useEffect(()=>setSearch(params.q??""),[params.q]);
 useEffect(()=>{const result=searchSchema.safeParse(search);if(!result.success){setSearchError(result.error.issues[0]?.message??"Invalid search");return}setSearchError("");const timer=window.setTimeout(()=>setUrl(previous=>{const latest=parseNoteParams(previous);const next={...latest,page:1};if(result.data)next.q=result.data;else delete next.q;return next.q===(latest.q??undefined)?previous:serializeNoteParams(next)},{replace:true}),300);return()=>clearTimeout(timer)},[search]);
 const query=useQuery({queryKey:queryKeys.notes.list(params),queryFn:({signal})=>api.notes.list(params,signal),placeholderData:previous=>previous}); const settings=useQuery({queryKey:queryKeys.settings.all,queryFn:api.settings.get}); const tags=useQuery({queryKey:queryKeys.tags.all,queryFn:api.tags.list});
 const set=<K extends keyof NoteListParams>(key:K,value:NoteListParams[K])=>{const next={...params,[key]:value,page:key==="page"?Number(value):1};if(value===undefined)delete next[key];setUrl(serializeNoteParams(next))};const zone=settings.data?.timezone??Intl.DateTimeFormat().resolvedOptions().timeZone;const local=(iso?:string)=>iso?DateTime.fromISO(iso,{setZone:true}).setZone(zone).toFormat("yyyy-LL-dd'T'HH:mm"):"";const instant=(value:string)=>value?(DateTime.fromISO(value,{zone}).toUTC().toISO()??undefined):undefined;
 return <Screen title="Notes" description="Search, filter, sort, and edit notes." action={<div className="flex gap-2"><Button onClick={()=>setEditing("new")}>New note</Button><Button variant="outline" onClick={()=>setEditing("series")}>New series</Button></div>}>
  {editing&&<div className="mb-6">{editing==="series"?<SeriesForm tags={tags.data??[]} timezone={zone} onSaved={()=>setEditing(null)} onCancel={()=>setEditing(null)}/>:editing==="new"?<NoteForm tags={tags.data??[]} timezone={zone} onSaved={()=>setEditing(null)} onCancel={()=>setEditing(null)}/>:editing.series_id?<RecurringEditChoice note={editing} tags={tags.data??[]} timezone={zone} onClose={()=>setEditing(null)}/>:<NoteForm note={editing} tags={tags.data??[]} timezone={zone} onSaved={()=>setEditing(null)} onCancel={()=>setEditing(null)}/>}</div>}
  <form className="mb-4 grid gap-3 rounded-lg border bg-white p-4 lg:grid-cols-6" onSubmit={e=>e.preventDefault()} aria-label="Note filters">
   <div className="lg:col-span-2"><Field label="Search title and body" error={searchError}><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="At least 3 characters"/></Field></div>
   <Field label="Status"><select className="min-h-10 rounded border px-2" value={params.active===undefined?"":String(params.active)} onChange={e=>set("active",e.target.value===""?undefined:e.target.value==="true")}><option value="">All</option><option value="true">Active</option><option value="false">Inactive</option></select></Field>
   <Field label="Tags (all selected must match)"><select multiple className="min-h-20 rounded border px-2" value={params.tag_id??[]} onChange={e=>set("tag_id",Array.from(e.target.selectedOptions,o=>o.value))}>{tags.data?.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></Field>
   <Field label="From"><Input type="datetime-local" value={local(params.starts_from)} onChange={e=>set("starts_from",instant(e.target.value))}/></Field><Field label="To"><Input type="datetime-local" value={local(params.starts_to)} onChange={e=>set("starts_to",instant(e.target.value))}/></Field>
   <Field label="Sort"><select className="min-h-10 rounded border px-2" value={params.sort} onChange={e=>set("sort",e.target.value as SortField)}><option value="starts_at">Note time</option><option value="updated_at">Modified</option></select></Field><Field label="Direction"><select className="min-h-10 rounded border px-2" value={params.direction} onChange={e=>set("direction",e.target.value as Direction)}><option value="asc">Oldest first</option><option value="desc">Newest first</option></select></Field>
  </form>
  {query.isPending?<p role="status">Loading notes…</p>:query.isError?<ErrorMessage error={query.error} label="Notes could not be loaded."/>:query.data.items.length===0?<Empty label="No matching notes."/>:<><NoteCards notes={query.data.items} timezone={settings.data?.timezone} onEdit={setEditing}/><Pagination page={query.data.page} pageSize={query.data.page_size} total={query.data.total} onPage={page=>set("page",page)}/></>}
 </Screen>;
}
function NoteCards({notes,timezone,onEdit}:{notes:Note[];timezone?:string | undefined;onEdit:(note:Note)=>void}){const {update,remove}=useNoteMutations();const [error,setError]=useState<unknown>();const seriesVersion=async(note:Note)=>note.series_id?(await api.series.get(note.series_id)).version:undefined;const act=async(note:Note)=>{setError(undefined);try{const expected_series_version=await seriesVersion(note);await update.mutateAsync({id:note.id,value:{title:note.title,body:note.body,starts_at:note.starts_at,active:!note.active,tag_ids:note.tags.map(t=>t.id),reminder_offsets_minutes:note.reminder_offsets_minutes,expected_version:note.version,...(expected_series_version===undefined?{}:{expected_series_version})}})}catch(e){setError(e)}};return <>{error&&<ErrorMessage error={error}/>}<ul className="grid gap-3">{notes.map(note=><li key={note.id} className="rounded-lg border bg-white p-4"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-bold">{note.title}</h2><time className="text-sm text-slate-600">{new Date(note.starts_at).toLocaleString(undefined,timezone?{timeZone:timezone}:undefined)}</time><p className="mt-2 whitespace-pre-wrap">{note.body}</p><div className="mt-2 flex gap-1">{note.tags.map(t=><span key={t.id} className="rounded-full px-2 py-0.5 text-xs text-white" style={{backgroundColor:t.color}}>{t.name}</span>)}</div></div><div className="flex items-start gap-2"><Button variant="outline" onClick={()=>onEdit(note)}>Edit</Button><Button variant="outline" onClick={()=>void act(note)}>{note.active?"Deactivate":"Activate"}</Button><Button variant="outline" onClick={()=>{if(confirm(`Move ${note.title} to trash?`))void seriesVersion(note).then(seriesVersion=>remove.mutateAsync({id:note.id,version:note.version,...(seriesVersion===undefined?{}:{seriesVersion})})).catch(setError)}}>Trash</Button></div></div></li>)}</ul></>}
function Pagination({page,pageSize,total,onPage}:{page:number;pageSize:number;total:number;onPage:(page:number)=>void}){const pages=Math.max(1,Math.ceil(total/pageSize));return <nav aria-label="Pagination" className="mt-4 flex items-center justify-between"><Button variant="outline" disabled={page<=1} onClick={()=>onPage(page-1)}>Previous</Button><span>Page {page} of {pages} · {total} results</span><Button variant="outline" disabled={page>=pages} onClick={()=>onPage(page+1)}>Next</Button></nav>}
export function UpcomingScreen(){const settings=useQuery({queryKey:queryKeys.settings.all,queryFn:api.settings.get});const tags=useQuery({queryKey:queryKeys.tags.all,queryFn:api.tags.list});const [opened,setOpened]=useState<Note>();const zone=settings.data?.timezone??Intl.DateTimeFormat().resolvedOptions().timeZone;return <Screen title="Upcoming" description="Today, this week, and past active notes."><UpcomingView timezone={zone} onOpen={setOpened}/><Dialog open={!!opened} onOpenChange={open=>{if(!open)setOpened(undefined)}}><DialogContent><DialogTitle>Edit note</DialogTitle><DialogDescription>Choose an edit scope for recurring notes.</DialogDescription>{opened&&(opened.series_id?<RecurringEditChoice note={opened} timezone={zone} tags={tags.data??[]} onClose={()=>setOpened(undefined)}/>:<NoteForm note={opened} timezone={zone} tags={tags.data??[]} onSaved={()=>setOpened(undefined)} onCancel={()=>setOpened(undefined)}/>)}</DialogContent></Dialog></Screen>}

export function TrashScreen(){const [page,setPage]=useState(1);const query=useQuery({queryKey:[...queryKeys.trash.all,page],queryFn:()=>api.notes.list({trash:true,page,page_size:20})});const {restore}=useNoteMutations();const [error,setError]=useState<unknown>();return <Screen title="Trash" description="Restore notes before permanent removal after 30 days.">{error!==undefined&&<ErrorMessage error={error}/>} {query.isPending?<p role="status">Loading trash…</p>:query.isError?<ErrorMessage error={query.error}/>:query.data.items.length===0?<Empty label="Trash is empty."/>:<><ul className="grid gap-3">{query.data.items.map(note=><li className="flex justify-between rounded-lg border bg-white p-4" key={note.id}><div><strong>{note.title}</strong><p className="text-sm text-slate-600">Deleted {note.deleted_at?new Date(note.deleted_at).toLocaleString():"recently"}</p></div><Button onClick={()=>void (note.series_id?api.series.get(note.series_id).then(series=>restore.mutateAsync({id:note.id,version:note.version,seriesVersion:series.version})):restore.mutateAsync({id:note.id,version:note.version})).catch(setError)}>Restore</Button></li>)}</ul><Pagination page={query.data.page} pageSize={query.data.page_size} total={query.data.total} onPage={setPage}/></>}</Screen>}

export function TagsScreen(){const query=useQuery({queryKey:queryKeys.tags.all,queryFn:api.tags.list});const mutations=useTagMutations();const [editing,setEditing]=useState<Tag>();const [name,setName]=useState("");const [color,setColor]=useState("#2563eb");const [error,setError]=useState("");const reset=()=>{setEditing(undefined);setName("");setColor("#2563eb")};const edit=(tag:Tag)=>{setEditing(tag);setName(tag.name);setColor(tag.color)};const submit=async(e:FormEvent)=>{e.preventDefault();const parsed=tagFormSchema.safeParse({name,color});if(!parsed.success){setError(parsed.error.issues[0]?.message??"Invalid tag");return;}setError("");try{if(editing)await mutations.update.mutateAsync({id:editing.id,value:{...parsed.data,expected_version:editing.version}});else await mutations.create.mutateAsync(parsed.data);reset()}catch(e){setError(e instanceof ApiError?e.body.message:"Save failed")}};return <Screen title="Tags" description="Create, rename, color, and delete tags."><form onSubmit={submit} className="mb-5 flex max-w-xl flex-wrap items-end gap-3 rounded border bg-white p-4"><Field label="Name" error={error||undefined}><Input value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Color"><Input aria-label="Color" type="color" value={color} onChange={e=>setColor(e.target.value)}/></Field><Button>{editing?"Save tag":"Create tag"}</Button>{editing&&<Button type="button" variant="outline" onClick={reset}>Cancel</Button>}</form>{query.isPending?<p role="status">Loading tags…</p>:query.isError?<ErrorMessage error={query.error}/>:query.data.length===0?<Empty label="No tags yet."/>:<ul className="grid max-w-xl gap-2">{query.data.map(t=><li className="flex items-center justify-between rounded border bg-white p-3" key={t.id}><span><span className="mr-2 inline-block size-3 rounded-full" style={{background:t.color}}/>{t.name}</span><span className="flex gap-2"><Button variant="outline" onClick={()=>edit(t)}>Edit</Button><Button variant="outline" onClick={()=>{if(confirm(`Delete tag ${t.name}? Notes keep their content.`))void mutations.remove.mutateAsync({id:t.id,version:t.version}).catch(e=>setError(e instanceof ApiError?e.body.message:"Delete failed"))}}>Delete</Button></span></li>)}</ul>}</Screen>}

export function SettingsScreen(){const query=useQuery({queryKey:queryKeys.settings.all,queryFn:api.settings.get});return <Screen title="Settings" description="Email and IANA display timezone.">{query.isPending?<p role="status">Loading settings…</p>:query.isError?<ErrorMessage error={query.error}/>:<SettingsForm settings={query.data}/>}</Screen>}
function SettingsForm({settings}:{settings:{email:string;timezone:string;version:number}}){const [email,setEmail]=useState(settings.email);const [timezone,setTimezone]=useState(settings.timezone);const [error,setError]=useState("");const mutation=useSettingsMutation();const submit=async(e:FormEvent)=>{e.preventDefault();const parsed=settingsFormSchema.safeParse({email,timezone,expected_version:settings.version});if(!parsed.success){setError(parsed.error.issues[0]?.message??"Invalid settings");return;}try{await mutation.mutateAsync(parsed.data);setError("")}catch(e){setError(e instanceof ApiError&&e.status===409?"Settings changed elsewhere. Your values are preserved; reload to compare.":e instanceof Error?e.message:"Save failed")}};return <form onSubmit={submit} className="grid max-w-lg gap-4 rounded-lg bg-white p-6 shadow-sm">{error&&<p role="alert" className="text-red-700">{error}</p>}<Field label="Email"><Input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></Field><Field label="IANA timezone"><Input value={timezone} onChange={e=>setTimezone(e.target.value)} placeholder="Europe/Budapest"/></Field><p className="text-sm text-slate-600">Timezone changes affect display only. Scheduled instants stay unchanged.</p><Button disabled={mutation.isPending}>{mutation.isPending?"Saving…":"Save settings"}</Button></form>}

export function NotificationsScreen(){const [page,setPage]=useState(1);const query=useQuery({queryKey:[...queryKeys.notifications.all,page],queryFn:()=>api.notifications(page,20)});return <Screen title="Notifications" description="Persistent reminder history. History never creates live toasts.">{query.isPending?<p role="status">Loading notifications…</p>:query.isError?<ErrorMessage error={query.error}/>:query.data.items.length===0?<Empty label="No notifications yet."/>:<><ul className="grid gap-2">{query.data.items.map(n=><li key={n.id} className="rounded border bg-white p-4"><strong>{n.title}</strong><p className="text-sm text-slate-600">Scheduled {new Date(n.scheduled_at).toLocaleString()} · recorded {new Date(n.created_at).toLocaleString()}</p></li>)}</ul><Pagination page={query.data.page} pageSize={query.data.page_size} total={query.data.total} onPage={setPage}/></>}</Screen>}
export function NotFoundScreen(){return <Screen title="Page not found" description="The requested page does not exist."/>}
function Empty({label}:{label:string}){return <p className="rounded-lg border border-dashed border-slate-300 bg-white p-8 text-slate-600">{label}</p>}
