import { useQuery } from "@tanstack/react-query"; import { api } from "../api/client"; import { queryKeys } from "../api/query-keys"; import { Dialog } from "../components/ui/dialog"; import { Button } from "../components/ui/button";
function Screen({title,description,action,children}:{title:string;description:string;action?:React.ReactNode;children?:React.ReactNode}){return <section><header className="mb-6 flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">{title}</h1><p className="mt-1 text-slate-600">{description}</p></div>{action}</header>{children??<div className="rounded-lg border border-dashed border-slate-300 bg-white p-8 text-slate-600">This workspace is ready for feature integration.</div>}</section>}
export function CalendarScreen(){return <Screen title="Calendar" description="Month, week, and day schedule views."/>}
export function NotesScreen(){const query=useQuery({queryKey:queryKeys.notes.list({page:1,page_size:50}),queryFn:()=>api.notes.list({page:1,page_size:50})});return <Screen title="Notes" description="Search, filter, sort, and edit notes." action={<Dialog title="New note" description="Note form integration point." trigger={<Button>New note</Button>}><p>The validated note form will open here.</p></Dialog>}>{query.isPending?<p role="status">Loading notes…</p>:query.isError?<p role="alert">Notes could not be loaded.</p>:query.data.items.length===0?<Empty label="No notes yet."/>:<ul>{query.data.items.map(n=><li key={n.id}>{n.title}</li>)}</ul>}</Screen>}
export function UpcomingScreen(){return <Screen title="Upcoming" description="Today, this week, and past active notes."/>}
export function TrashScreen(){return <Screen title="Trash" description="Restore notes before permanent removal after 30 days."/>}
export function SettingsScreen(){const query=useQuery({queryKey:queryKeys.settings.all,queryFn:api.settings.get});return <Screen title="Settings" description="Email and IANA display timezone.">{query.isPending?<p role="status">Loading settings…</p>:query.isError?<p role="alert">Settings could not be loaded.</p>:<dl className="grid max-w-lg gap-4 rounded-lg bg-white p-6 shadow-sm"><div><dt className="text-sm text-slate-500">Email</dt><dd>{query.data.email}</dd></div><div><dt className="text-sm text-slate-500">Timezone</dt><dd>{query.data.timezone}</dd></div></dl>}</Screen>}
export function TagsScreen(){const query=useQuery({queryKey:queryKeys.tags.all,queryFn:api.tags.list});return <Screen title="Tags" description="Create, rename, color, and delete tags.">{query.isPending?<p role="status">Loading tags…</p>:query.isError?<p role="alert">Tags could not be loaded.</p>:query.data.items.length===0?<Empty label="No tags yet."/>:<ul>{query.data.items.map(t=><li key={t.id}><span className="mr-2 inline-block size-3 rounded-full" style={{background:t.color}}/>{t.name}</li>)}</ul>}</Screen>}
export function NotificationsScreen(){return <Screen title="Notifications" description="Persistent reminder history. History never creates live toasts."/>}
export function NotFoundScreen(){return <Screen title="Page not found" description="The requested page does not exist."/>}
function Empty({label}:{label:string}){return <p className="rounded-lg border border-dashed border-slate-300 bg-white p-8 text-slate-600">{label}</p>}
