import type { ApiErrorBody, Note, NoteListParams, NoteUpdate, NoteWrite, Page, Settings, SettingsUpdate, Tag, TagWrite, RecurrenceSeries, SeriesCreate, SeriesSplit, CalendarParams, UpcomingResponse, Notification, TrashGroup, RecurrencePreview } from "./contracts";
export class ApiError extends Error { constructor(public status:number, public body:ApiErrorBody){ super(body.message); this.name="ApiError"; } }
function queryString(params: object): string { const query=new URLSearchParams(); Object.entries(params).forEach(([key,value])=>{ if(value===undefined) return; (Array.isArray(value)?value:[value]).forEach(item=>query.append(key,String(item))); }); const value=query.toString(); return value?`?${value}`:""; }
export async function request<T>(path:string, init:RequestInit={}):Promise<T>{ const headers=new Headers(init.headers); if(init.body) headers.set("content-type","application/json"); headers.set("accept","application/json"); const response=await fetch(`/api/v1${path}`,{...init,headers}); if(!response.ok){ let body:ApiErrorBody; try { body=await response.json() as ApiErrorBody; } catch { body={code:"http_error",message:`Request failed (${response.status})`,field_errors:null,current:null}; } throw new ApiError(response.status,body); } if(response.status===204) return undefined as T; return response.json() as Promise<T>; }
export const api={
 notes:{list:(params:NoteListParams={},signal?:AbortSignal)=>request<Page<Note>>(`/notes${queryString(params)}`,signal?{signal}:{}),get:(id:string)=>request<Note>(`/notes/${id}`),create:(value:NoteWrite)=>request<Note>("/notes",{method:"POST",body:JSON.stringify(value)}),update:(id:string,value:NoteUpdate)=>request<Note>(`/notes/${id}`,{method:"PATCH",body:JSON.stringify(value)}),remove:(id:string,expectedVersion:number,expectedSeriesVersion?:number)=>request<void>(`/notes/${id}${queryString({expected_version:expectedVersion,expected_series_version:expectedSeriesVersion})}`,{method:"DELETE"}),restore:(id:string,expected_version:number,expected_series_version?:number)=>request<Note>(`/notes/${id}/restore`,{method:"POST",body:JSON.stringify({expected_version,expected_series_version})})},
 tags:{list:()=>request<Tag[]>("/tags"),create:(value:TagWrite)=>request<Tag>("/tags",{method:"POST",body:JSON.stringify(value)}),update:(id:string,value:TagWrite&{expected_version:number})=>request<Tag>(`/tags/${id}`,{method:"PATCH",body:JSON.stringify(value)}),remove:(id:string,expectedVersion:number)=>request<void>(`/tags/${id}?expected_version=${expectedVersion}`,{method:"DELETE"})},
 settings:{get:()=>request<Settings>("/settings"),update:(value:SettingsUpdate)=>request<Settings>("/settings",{method:"PATCH",body:JSON.stringify(value)})},
 series:{preview:(value:Pick<SeriesCreate,"local_start"|"timezone"|"frequency"|"end_date">)=>request<RecurrencePreview>("/series/preview",{method:"POST",body:JSON.stringify(value)}),create:(value:SeriesCreate)=>request<RecurrenceSeries>("/series",{method:"POST",body:JSON.stringify(value)}),get:(id:string)=>request<RecurrenceSeries>(`/series/${id}`),split:(id:string,value:SeriesSplit)=>request<RecurrenceSeries>(`/series/${id}/split`,{method:"POST",body:JSON.stringify(value)}),trash:(id:string,expected_series_version:number)=>request<void>(`/series/${id}/trash`,{method:"POST",body:JSON.stringify({expected_series_version})}),restore:(id:string,expected_series_version:number)=>request<RecurrenceSeries>(`/series/${id}/restore`,{method:"POST",body:JSON.stringify({expected_series_version})})},
 calendar:(params:CalendarParams)=>request<Note[]>(`/calendar${queryString(params)}`),
 upcoming:(page=1,page_size=50)=>request<UpcomingResponse>(`/upcoming${queryString({page,page_size})}`),
 notifications:(page=1,page_size=50)=>request<Page<Notification>>(`/notifications${queryString({page,page_size})}`)
 ,trash:{list:(page=1,page_size=20)=>request<Page<TrashGroup>>(`/trash/groups${queryString({page,page_size})}`),restoreAction:(id:string,expected_series_version:number)=>request<RecurrenceSeries>(`/trash/actions/${id}/restore`,{method:"POST",body:JSON.stringify({expected_series_version})})}
};
